### ISSUE TITLE
[openqa-revtui] Crash while scrolling...

### ISSUE THREAD

**Issue by cfconrad** [os-autoinst/openqa-mon#55]
I scrolled around using `openqa-revtui containers.toml`

```bash
> rpm -qi openqa-mon
Name        : openqa-mon
Version     : 0.23
Release     : lp153.5.5
Architecture: x86_64
Install Date: Thu 12 Aug 2021 02:05:54 PM CEST
Group       : Unspecified
Size        : 22995176
License     : GPL-3.0-or-later
Signature   : RSA/SHA256, Sat 24 Jul 2021 12:31:09 PM CEST, Key ID 4e9d7216c28082f4
Source RPM  : openqa-mon-0.23-lp153.5.5.src.rpm
Build Date  : Sat 24 Jul 2021 12:30:32 PM CEST
Build Host  : lamb22
Relocations : (not relocatable)
Vendor      : obs://build.opensuse.org/home:ph03nix
URL         : https://github.com/grisu48/openqa-mon/
Summary     : CLI monitoring utility for openQA
Description :
openqa-mon is a CLI monitoring client for openqa written in plain go.
Distribution: home:ph03nix / openSUSE_Leap_15.3
```

```bash
fatal error: concurrent map read and map write

goroutine 32 [running]:
runtime.throw(0x560d399173aa, 0x21)
        /usr/lib64/go/1.16/src/runtime/panic.go:1117 +0x74 fp=0xc00028d240 sp=0xc00028d210 pc=0x560d39696b74
runtime.mapaccess2_fast64(0x560d39abf9e0, 0xc000192180, 0x67838f, 0x560d3991153c, 0x13)
        /usr/lib64/go/1.16/src/runtime/map_fast64.go:61 +0x1ac fp=0xc00028d268 sp=0xc00028d240 pc=0x560d3967328c
main.(*TUI).formatJobLine(0xc0001582c0, 0x520, 0x0, 0x560d39cdf4f0, 0x0, 0x0, 0x560d39cdf4f0, 0x0, 0x0, 0x560d39cdf4f0, ...)
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/cmd/openqa-revtui/tui.go:508 +0x254 fp=0xc00028d470 sp=0xc00028d268 pc=0x560d3990aa54
main.(*TUI).printJobsByGroup(0xc0001582c0, 0xee, 0x2d, 0x0)
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/cmd/openqa-revtui/tui.go:334 +0xce8 fp=0xc00028dd60 sp=0xc00028d470 pc=0x560d39909688
main.(*TUI).Update(0xc0001582c0)
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/cmd/openqa-revtui/tui.go:434 +0x477 fp=0xc00028dea8 sp=0xc00028dd60 pc=0x560d39909eb7
main.tui_main.func1(0xc00012e041)
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/cmd/openqa-revtui/openqa-revtui.go:497 +0x177 fp=0xc00028df60 sp=0xc00028dea8 pc=0x560d3990c0b7
main.(*TUI).readInput(0xc0001582c0)
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/cmd/openqa-revtui/tui.go:224 +0xda fp=0xc00028dfd8 sp=0xc00028df60 pc=0x560d39907eba
runtime.goexit()
        /usr/lib64/go/1.16/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00028dfe0 sp=0xc00028dfd8 pc=0x560d396cce81
created by main.(*TUI).Start
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/cmd/openqa-revtui/tui.go:232 +0x125

goroutine 1 [chan receive, 197 minutes]:
main.(*TUI).awaitTerminationSignal(0xc0001582c0)
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/cmd/openqa-revtui/tui.go:267 +0xec
main.tui_main(0xc0001582c0, 0xc000176040, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa, 0x0)
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/cmd/openqa-revtui/openqa-revtui.go:563 +0x6d9
main.main()
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/cmd/openqa-revtui/openqa-revtui.go:417 +0x54a

goroutine 59 [semacquire]:
sync.runtime_SemacquireMutex(0xc0001582e4, 0xc00023e000, 0x1)
        /usr/lib64/go/1.16/src/runtime/sema.go:71 +0x49
sync.(*Mutex).lockSlow(0xc0001582e0)
        /usr/lib64/go/1.16/src/sync/mutex.go:138 +0x10f
sync.(*Mutex).Lock(...)
        /usr/lib64/go/1.16/src/sync/mutex.go:81
main.(*TUI).Update(0xc0001582c0)
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/cmd/openqa-revtui/tui.go:384 +0xb66
main.refreshJobs(0xc0001582c0, 0xc000176040, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa, 0x0, ...)
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/cmd/openqa-revtui/openqa-revtui.go:452 +0x590
main.tui_main.func2(0xc0001582c0, 0xc000176040, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa)
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/cmd/openqa-revtui/openqa-revtui.go:556 +0x7c
created by main.tui_main
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/cmd/openqa-revtui/openqa-revtui.go:553 +0x832

goroutine 16 [chan receive, 197 minutes]:
main.(*TUI).awaitTerminationSignal.func1(0xc0003ab680, 0xc0001582c0)
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/cmd/openqa-revtui/tui.go:263 +0x45
created by main.(*TUI).awaitTerminationSignal
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/cmd/openqa-revtui/tui.go:262 +0xd1

goroutine 58 [chan receive]:
github.com/grisu48/gopenqa.(*RabbitMQSubscription).Receive(...)
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/vendor/github.com/grisu48/gopenqa/rabbitmq.go:48
github.com/grisu48/gopenqa.(*RabbitMQSubscription).ReceiveJobStatus(0xc0000b9400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/vendor/github.com/grisu48/gopenqa/rabbitmq.go:74 +0xdf
main.registerRabbitMQ.func1(0xc0000b9400, 0xc0001582c0)
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/cmd/openqa-revtui/openqa-revtui.go:362 +0x85
created by main.registerRabbitMQ
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/cmd/openqa-revtui/openqa-revtui.go:360 +0x2a5

goroutine 33 [chan receive, 2 minutes]:
main.(*TUI).Start.func1(0xc0001582c0)
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/cmd/openqa-revtui/tui.go:238 +0xa5
created by main.(*TUI).Start
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/cmd/openqa-revtui/tui.go:234 +0x14a

goroutine 45 [syscall, 2 minutes]:
os/signal.signal_recv(0x560d39b1e700)
        /usr/lib64/go/1.16/src/runtime/sigqueue.go:168 +0xa5
os/signal.loop()
        /usr/lib64/go/1.16/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        /usr/lib64/go/1.16/src/os/signal/signal.go:151 +0x46

goroutine 69 [IO wait]:
internal/poll.runtime_pollWait(0x7f0cc404c508, 0x72, 0xffffffffffffffff)
        /usr/lib64/go/1.16/src/runtime/netpoll.go:222 +0x65
internal/poll.(*pollDesc).wait(0xc0008ea318, 0x72, 0x2200, 0x2285, 0xffffffffffffffff)
        /usr/lib64/go/1.16/src/internal/poll/fd_poll_runtime.go:87 +0x47
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib64/go/1.16/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0008ea300, 0xc000472000, 0x2285, 0x2285, 0x0, 0x0, 0x0)
        /usr/lib64/go/1.16/src/internal/poll/fd_unix.go:166 +0x1d8
net.(*netFD).Read(0xc0008ea300, 0xc000472000, 0x2285, 0x2285, 0x2278, 0xc0006441a0, 0xd)
        /usr/lib64/go/1.16/src/net/fd_posix.go:55 +0x51
net.(*conn).Read(0xc00012e3f0, 0xc000472000, 0x2285, 0x2285, 0x0, 0x0, 0x0)
        /usr/lib64/go/1.16/src/net/net.go:183 +0x93
crypto/tls.(*atLeastReader).Read(0xc0002d8b28, 0xc000472000, 0x2285, 0x2285, 0x2278, 0xc000103000, 0x0)
        /usr/lib64/go/1.16/src/crypto/tls/conn.go:776 +0x65
bytes.(*Buffer).ReadFrom(0xc000644278, 0x560d39b1ba98, 0xc0002d8b28, 0x560d3966c167, 0x560d39ac79e0, 0x560d39b06100)
        /usr/lib64/go/1.16/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc000644000, 0x560d39b1bd38, 0xc00012e3f0, 0x5, 0xc00012e3f0, 0x8)
        /usr/lib64/go/1.16/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc000644000, 0x0, 0x0, 0x0)
        /usr/lib64/go/1.16/src/crypto/tls/conn.go:605 +0x125
crypto/tls.(*Conn).readRecord(...)
        /usr/lib64/go/1.16/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc000644000, 0xc00054a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib64/go/1.16/src/crypto/tls/conn.go:1276 +0x173
bufio.(*Reader).Read(0xc0003ab380, 0xc000367ba0, 0x7, 0x7, 0xc00004ce60, 0x560d3966eb9a, 0x7)
        /usr/lib64/go/1.16/src/bufio/bufio.go:227 +0x224
io.ReadAtLeast(0x560d39b1b9b8, 0xc0003ab380, 0xc000367ba0, 0x7, 0x7, 0x7, 0xc00004ced8, 0x560d39666335, 0xc00051c660)
        /usr/lib64/go/1.16/src/io/io.go:328 +0x89
io.ReadFull(...)
        /usr/lib64/go/1.16/src/io/io.go:347
github.com/streadway/amqp.(*reader).ReadFrame(0xc00004cf40, 0xc00004cf50, 0xc000367b5a, 0x0, 0x0)
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/vendor/github.com/streadway/amqp/read.go:49 +0x77
github.com/streadway/amqp.(*Connection).reader(0xc000203b80, 0x7f0cec2112e0, 0xc000644000)
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/vendor/github.com/streadway/amqp/connection.go:521 +0xdc
created by github.com/streadway/amqp.Open
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/vendor/github.com/streadway/amqp/connection.go:233 +0x26c

goroutine 57 [select]:
github.com/streadway/amqp.(*Connection).heartbeater(0xc000203b80, 0x2540be400, 0xc0003ab3e0)
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/vendor/github.com/streadway/amqp/connection.go:551 +0x18d
created by github.com/streadway/amqp.(*Connection).openTune
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/vendor/github.com/streadway/amqp/connection.go:782 +0x465

goroutine 46 [chan receive]:
github.com/streadway/amqp.(*consumers).buffer(0xc00006bd10, 0xc0000225a0, 0xc000022120)
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/vendor/github.com/streadway/amqp/consumers.go:61 +0x365
created by github.com/streadway/amqp.(*consumers).add
        /home/abuild/rpmbuild/BUILD/openqa-mon-0.23/vendor/github.com/streadway/amqp/consumers.go:97 +0x165

goroutine 3437 [select]:
net/http.(*persistConn).writeLoop(0xc0001485a0)
        /usr/lib64/go/1.16/src/net/http/transport.go:2382 +0xf9
created by net/http.(*Transport).dialConn
        /usr/lib64/go/1.16/src/net/http/transport.go:1744 +0xc9c

goroutine 3436 [IO wait]:
internal/poll.runtime_pollWait(0x7f0cc404c6d8, 0x72, 0xffffffffffffffff)
        /usr/lib64/go/1.16/src/runtime/netpoll.go:222 +0x65
internal/poll.(*pollDesc).wait(0xc00017a618, 0x72, 0x2e00, 0x2e03, 0xffffffffffffffff)
        /usr/lib64/go/1.16/src/internal/poll/fd_poll_runtime.go:87 +0x47
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib64/go/1.16/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00017a600, 0xc000339000, 0x2e03, 0x2e03, 0x0, 0x0, 0x0)
        /usr/lib64/go/1.16/src/internal/poll/fd_unix.go:166 +0x1d8
net.(*netFD).Read(0xc00017a600, 0xc000339000, 0x2e03, 0x2e03, 0x2dfe, 0xc000339000, 0x5)
        /usr/lib64/go/1.16/src/net/fd_posix.go:55 +0x51
net.(*conn).Read(0xc000010060, 0xc000339000, 0x2e03, 0x2e03, 0x0, 0x0, 0x0)
        /usr/lib64/go/1.16/src/net/net.go:183 +0x93
crypto/tls.(*atLeastReader).Read(0xc0002d8078, 0xc000339000, 0x2e03, 0x2e03, 0xc0001df9f8, 0xc000080000, 0x0)
        /usr/lib64/go/1.16/src/crypto/tls/conn.go:776 +0x65
bytes.(*Buffer).ReadFrom(0xc000644978, 0x560d39b1ba98, 0xc0002d8078, 0x560d3966c167, 0x560d39ac79e0, 0x560d39b06100)
        /usr/lib64/go/1.16/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc000644700, 0x560d39b1bd38, 0xc000010060, 0x5, 0xc000010060, 0x203000)
        /usr/lib64/go/1.16/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc000644700, 0x0, 0x0, 0x560d396998de)
        /usr/lib64/go/1.16/src/crypto/tls/conn.go:605 +0x125
crypto/tls.(*Conn).readRecord(...)
        /usr/lib64/go/1.16/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc000644700, 0xc00059e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib64/go/1.16/src/crypto/tls/conn.go:1276 +0x173
net/http.(*persistConn).Read(0xc0001485a0, 0xc00059e000, 0x1000, 0x1000, 0xc000afc300, 0xc0001dfd40, 0x560d39666335)
        /usr/lib64/go/1.16/src/net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0xc0002d3380)
        /usr/lib64/go/1.16/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0xc0002d3380, 0x1, 0x0, 0x1, 0x4, 0x1, 0x3)
        /usr/lib64/go/1.16/src/bufio/bufio.go:139 +0x51
net/http.(*persistConn).readLoop(0xc0001485a0)
        /usr/lib64/go/1.16/src/net/http/transport.go:2083 +0x1aa
created by net/http.(*Transport).dialConn
        /usr/lib64/go/1.16/src/net/http/transport.go:1743 +0xc77

```

**Comment by grisu48** [comment]
This issue should have been resolved with the latest changes in [gopenqa](https://github.com/grisu48/gopenqa). Closing issue, feel free to reopen if it happens again.
