### ISSUE TITLE
check -c parameter for numeric value, or give error message when wrong

### ISSUE THREAD

**Issue by ilmanzo** [os-autoinst/openqa-mon#74]
problem is likely at line 160:
https://github.com/grisu48/openqa-mon/blob/ae22ba16401c5d9187b6393652c5c0243bc1bda7/cmd/openqa-mon/openqa-mon.go#L160

to reproduce:

```
$ openqa-mon  -c                                                                          
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.expandArguments({0xc000016050, 0x1, 0x558b8d8a77c0?})
	/home/abuild/rpmbuild/BUILD/openqa-mon-0.25/cmd/openqa-mon/openqa-mon.go:160 +0xa8d
main.main()
	/home/abuild/rpmbuild/BUILD/openqa-mon-0.25/cmd/openqa-mon/openqa-mon.go:246 +0x7b

```

**Comment by grisu48** [comment]
Yes indeed, thanks for the issue and the PR!
